telegram.bot.token=8742438191:AAH_Lz5I_h4EQWCfUH8mVyAImi3ErpqKxmc
telegram.bot.username=gymNutritionTracker

ninjas.base.url=https://api-ninjas.com/api/
ninjas.exercises.url=https://api.api-ninjas.com/v1/exercises?muscle=
ninjas.api.key=LB3xQk510AGs9WfOj5Q99fA9bSw1kbylnpw4Ei36

edaman.food.url=https://api.edamam.com/api/food-database/v2/parser
edaman.api.key=dca950bd7e426539e97f4bd95dde23ea
edaman.application.id=076731b8


connection.driver_class=org.postgresql.Driver
connection.url=jdbc:postgresql://localhost:5432/SmartGym
connection.username=SmartGym
connection.password=SmartGym

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider

hikari.maximumPoolSize=10
hikari.minimumIdle=2
hikari.connectionTimeout=30000





