CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT UNIQUE,
    username VARCHAR(255) NOT NULL,
    age INTEGER,
    weight REAL,
    height REAL,
    goal VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
    );
create table if not exists workouts(
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    workout_date timestamp NOT NUll,
    type varchar(255) NOT NULL,--силовая,кардио,йога
    notes varchar(255) --заметки
);
 create table if not exists food_entries(
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),--кто ел
    entry_date timestamp NOT NULL, --когда
    food_name varchar(255) NOT NULL,
    calories REAL,
    protein REAL,
    fat REAL,
    carbs REAL,
    quantity REAL, --сколько сьел
    unit unit_type-- единица измерения(г,мл,шт)
);
create table if not exists NUTRITION_GOALS(
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    daily_calories REAL NOT NULL, --норма каллорий
    daily_protein REAL NOT NULL,-- норма бжу
    daily_fat REAL NOT NULL,-- норма бжу
    daily_carbs REAL NOT NULL, -- норма бжу
    start_date timestamp,--с какого по какой день
    end_date timestamp
);
create table if not exists EXERCISES( --справочник упражнений
    id bigint generated by default as identity primary key,
    name varchar(255) NOT NULL,
    muscle_group varchar(255) NOT NULL,
    description varchar,-- описание/инструкция
    difficulty varchar,--сложность (easy/medium/hard)
    equipment varchar--оборудование (штанга/гантели/без)
    );

create table if not exists WORKOUT_EXERCISES(
    id bigint generated by default as identity primary key,
    workout_id bigint references workouts(id),--какой тип тренировки аля
    exercise_id bigint references EXERCISES(id),--какое упражнение
    sets int, --кол-во подходов
    reps int,--повторения
    weight REAL,
    duration interval --длительность (для кардио)
    check((sets is not null and reps is not null)
    or (duration is not null))
);












